dist: trusty
env:
    global:
        # SPREAD_LINODE_KEY
        - secure: 2M77bK+jY3DEDue9yltn6jICylFzJ2xsvoubYfdyYRuMx2N1eEUVuXm+9F6Xle6LkgcOqQsG4r7JrcRb3yK3npNUx+MVs1KFhdxGzBQEZpYxNwijwUyGKP2X6c/ah+sCD/Lor1fnaly2Sqs3Rd8NMhU7qm6CM5Y0f6CJyEVHOfJrsfoX5XCj+sy8QPbFyGYI+BL7jwnFcnDs+IBgEfSxNEPcD7jtyT53aHta/JF8cnZXpUNHe+qyLH/uUGJxvJGY0PVX0sTGI0sjx1IzcgeGaB2L3dUPj/t/8IZBiXY+51TWJL6VTqjKTVdRSawYQD7G1NlnSKKzMJOhiscnNyIHUMROlfz43DCL0Q8eKLDF1QY9aQz/x7RVtzzAsz4jmlw9rp27YG3/gXogHMfOBheJrbIRoAvuFZ6u37N9NlHDODe6djZfg92w9f3OyUzC/uWpAZxzYUb+emMLgHsgbHNS6m20tZ8ZiqP3ivBF+UKBEPgk02+/WiNEbmiMVMIIOYcGCxNHLgT8zEaWUhEJis0bsVp/+TmegwuJqkPZpREAlFEMHaATz4qS5Sb14S4JmbxxxO3OOrDVtEYEe8lYbQgMry/BV8kqBx45jHAbrvSHYY+Acku3kynEJF+dJcN8j10lgNva0KEVbgnh6Kz4riN8i3etk/IRuyw83svw8HInRtA=
script:
    - mkdir -p bin
    - ( cd bin && curl -s -O https://niemeyer.s3.amazonaws.com/spread-amd64.tar.gz && tar xzvf spread-amd64.tar.gz )
    - cp -ar custom/. target/
    - cd target && ../bin/spread -v
