#!/bin/sh

mkdir -p bin
( cd bin &&  wget https://niemeyer.s3.amazonaws.com/spread-amd64.tar.gz -O spread.tar.gz && tar xzvf spread.tar.gz )
git clone https://github.com/snapcore/snapd target

export SPREAD_MODIFY_CORE_SNAP_FOR_REEXEC=0
export SPREAD_TRUST_TEST_KEYS=false
export SPREAD_SRU_VALIDATION=1
export SPREAD_CORE_CHANNEL=edge

../bin/spread -v linode:ubuntu-16.04-64:tests/main/
