name: spread-cron

version: 1.0

summary: Basic support for launching spread-cron jobs

description: |
    This snap declares a simple daemon for checking the jobs
    defined in the snapcore/spread-cron branches.

    For each of the jobs, the checker/run script is executed,
    it looks for changes on external resources, extracting the
    relevant information according to the options file. In case
    a change in the external resource related to a particular
    branch is detected, then a commit is pushed to that branch,
    so that the travis execution is triggered.

    The snap must be able to push to the snapcore/spread-cron repo,
    the credentials for doing so are passed to the snap via a
    configure hook

        $ snap set spread-cron username=<username> password=<password>

apps:
    cron:
        command: bin/cron
        daemon: simple
        plugs: [network]

parts:
    git:
        plugin: make
        source: .
        stage-packages:
            - curl
            - libcurl4-openssl-dev
        build-packages:
            - asciidoc
            - curl
            - cvs
            - cvsps
            - docbook-xsl
            - libcurl4-openssl-dev
            - libdbd-sqlite3-perl
            - libsvn-perl
            - libyaml-perl
            - subversion
            - xmlto
        snap:
            - bin/
            - meta/hooks
            - usr/
