#!/bin/sh

mv sa.json target
( cd target && SPREAD_SNAPD_SNAP_ID=master spread google:ubuntu-22.04-64:tasks/upload-snapd-snap-to-gce )

git clone https://github.com/snapcore/snapd
export NO_DELTA=1
export SPREAD_USE_SNAPD_SNAP_URL=https://storage.googleapis.com/snapd-spread-tests/snapd-tests/snaps/snapd_master.snap
cd snapd && spread -no-debug-output google:tests/ google-core:tests/ google-distro-1:tests/ google-distro-2:tests/
