#!/bin/bash
set +x

SNAPD_GIT_URL=${1:-https://github.com/canonical/snapd.git}
SNAPD_GIT_BRANCH=${2:-master}
SNAPD_TESTS=${3:-tests/smoke/}


DIR="$(mktemp -d)"
cd "$DIR"

git clone "$SNAPD_GIT_URL" snapd
cd snapd
git checkout "$SNAPD_GIT_BRANCH"

export SPREAD_HTTPS_PROXY=http://squid.internal:3128
export SPREAD_HTTP_PROXY=http://squid.internal:3128

export SPREAD_USE_PREBUILT_SNAPD_SNAP=true
export SPREAD_USE_SNAPD_SNAP_URL=https://storage.googleapis.com/snapd-spread-tests/snapd-tests/snaps/snapd_master.snap

spread qemu:ubuntu-18.04-64:"$SNAPD_TESTS" qemu:ubuntu-20.04-64:"$SNAPD_TESTS" qemu:ubuntu-22.04-64:"$SNAPD_TESTS"
