#!/bin/sh

if [ -z "$S390X_ENDPOINT" ]; then
	echo "S390X endpoint cannot be empty, exiting..."
	exit 1
fi


if ! [ -f "./s390x_key" ]; then
	echo "S390X key file does not exist, exiting..."
	exit 1
fi
KEY_FILE="./s390x_key"

echo "Creating temporal directory"
TEMP_DIR=$(ssh -i "$KEY_FILE" -o ConnectTimeout=10 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no "ubuntu@$S390X_ENDPOINT" -- mktemp -d)

echo "Deploying remote executor"
scp -i "$KEY_FILE" -o ConnectTimeout=10 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ./remote-executor "ubuntu@$S390X_ENDPOINT":"$TEMP_DIR"

echo "Executing tests"
ssh -i "$KEY_FILE" -o ConnectTimeout=10 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no "ubuntu@$S390X_ENDPOINT" -- "$TEMP_DIR"/remote-executor
SPREAD_RESULT=$?

echo "Cleaning up the environment"
ssh -i "$KEY_FILE" -o ConnectTimeout=10 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no "ubuntu@$S390X_ENDPOINT" -- rm -rf /tmp/tmp.*

# echo "Cleaning up spread and qemu instances"
# ssh -i "$KEY_FILE" -o ConnectTimeout=10 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no "ubuntu@$S390X_ENDPOINT" -- pkill spread
# ssh -i "$KEY_FILE" -o ConnectTimeout=10 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no "ubuntu@$S390X_ENDPOINT" -- pkill qemu-system

exit $SPREAD_RESULT
