summary: Update the gce test bucket

systems: [ubuntu-22.04-64]

environment:
    GOVERSION: 1.22/stable
    GOHOME: /home/test
    GOPATH: $GOHOME
    SPREAD_PATH: $GOHOME/src/github.com/snapcore/spread
    PATH: $GOHOME/bin:$PATH
    # Need CGO_ENABLED=0 to avoid GLIBC not found error
    CGO_ENABLED: 0

prepare: |
    # Download spread code
    apt install -y git
    mkdir -p "$SPREAD_PATH"
    git clone https://github.com/canonical/spread.git "$SPREAD_PATH"

    # Install go dependencies
    apt remove -y golang golang-go || true
    snap install go --classic --channel "$GOVERSION"

    # Prepare to upload files to gs bucket
    if ! command -v gcloud &>/dev/null; then
        snap install --classic google-cloud-sdk
    fi
    gcloud auth activate-service-account --key-file="$PROJECT_PATH/sa.json"
    rm -f "$PROJECT_PATH/sa.json"

restore: |
    rm -rf godeb spread
    rm -f "$PROJECT_PATH/sa.json" "$SPREAD_PATH"/spread-amd64.tar.gz
   
execute: |
    # Build spread
    ( cd "$SPREAD_PATH/cmd/spread" && go get && go install )

    # Check spread is created and it is executable
    test -x "$GOHOME"/bin/spread

    # Back up previous spread if it is published
    if gsutil ls gs://snapd-spread-tests/spread/spread-amd64.tar.gz; then
        gsutil cp gs://snapd-spread-tests/spread/spread-amd64.tar.gz gs://snapd-spread-tests/spread/spread-amd64-old.tar.gz
    fi

    # Prepare tmp spreadand push to gce bucket
    tar -czf ./spread-amd64.tar.gz --directory="$GOHOME"/bin spread
    if gsutil ls gs://snapd-spread-tests/spread/spread-amd64-tmp.tar.gz; then
        gsutil rm gs://snapd-spread-tests/spread/spread-amd64-tmp.tar.gz
    fi
    gsutil cp spread-amd64.tar.gz gs://snapd-spread-tests/spread/spread-amd64-tmp.tar.gz

    # check spread is executable and works
    wget https://storage.googleapis.com/snapd-spread-tests/spread/spread-amd64-tmp.tar.gz
    tar -xvzf spread-amd64-tmp.tar.gz
    test -x ./spread
    ./spread -h 2>&1 | MATCH "Usage of"

    # Finally replace the new spread
    if gsutil ls gs://snapd-spread-tests/spread/spread-amd64.tar.gz; then
        gsutil rm gs://snapd-spread-tests/spread/spread-amd64.tar.gz
    fi
    gsutil mv gs://snapd-spread-tests/spread/spread-amd64-tmp.tar.gz gs://snapd-spread-tests/spread/spread-amd64.tar.gz
