#!/bin/sh
set -e

git clone https://github.com/canonical/snapd target
cd target

export SPREAD_EXPERIMENTAL_FEATURES=gate-auto-refresh-hook
export SPREAD_USE_SNAPD_SNAP_URL=https://storage.googleapis.com/snapd-spread-tests/snapd-tests/snaps/snapd_master_amd64.snap

spread -v google:ubuntu-18.04-64:tests/ google:ubuntu-20.04-64:tests/ google:ubuntu-21.10-64:tests/ google:ubuntu-core-20-64:tests/ 
