#!/bin/sh
set -e

git clone https://github.com/canonical/snapd target
cd target

export SPREAD_CORE_CHANNEL=stable
export SPREAD_NEW_CORE_CHANNEL=edge
export SPREAD_ENABLE_KVM=true
export SPREAD_USE_SNAPD_SNAP_URL=https://storage.googleapis.com/snapd-spread-tests/snapd-tests/snaps/snapd_master.snap

spread -v google-nested:ubuntu-16.04-64:tests/nested/core/ google-nested:ubuntu-16.04-64:tests/nested/manual/
