#!/bin/sh

git clone https://github.com/snapcore/snapd target

# determine branch
branch=master
url=$(curl -s -H 'X-Ubuntu-Architecture: amd64' -H 'X-Ubuntu-Series: 16' https://search.apps.ubuntu.com/api/v1/snaps/details/core?channel=$SPREAD_CORE_CHANNEL | jq -j '.anon_download_url')
curl -L -o core.snap $url
sudo unsquashfs -d /tmp/unpack core.snap
version=$(cut -d'=' -f 2 < /tmp/unpack/usr/lib/snapd/info | cut -d'+' -f 1)
major=$(echo $version | cut -d'.' -f 1)
minor=$(echo $version | cut -d'.' -f 2)
release_branch="release/${major}.${minor}"

cd target
if git branch -r | grep "$release_branch"; then
    git checkout "$release_branch"
fi
export SPREAD_CORE_CHANNEL=stable

spread -v google:ubuntu-16.04-64 google:ubuntu-core-16-64
