#!/bin/sh
set -e

git clone https://github.com/canonical/snapd target
cd target

export SPREAD_NEW_CORE_CHANNEL=edge
export SPREAD_ENABLE_KVM=true

spread -v google-nested-dev:ubuntu-24.04-64:tests/nested/core/ google-nested-dev:ubuntu-24.04-64:tests/nested/manual/
