#!/bin/sh

set -ex

. $(dirname "$0")/../options

if [ -z "$pattern_extractor" ] | [ -z "$message" ]; then
    echo "Required fields pattern_extractor and message not found in ../options"
    exit 1
fi

new_value=$(eval "$pattern_extractor")
if [ -z "$new_value" ]; then
    echo "$pattern_extractor didn't found anything"
    exit 1
fi

old_value_path=$(dirname "$0")/old_value
trap 'echo $new_value | tee $old_value_path' HUP INT TERM EXIT
old_value=$(cat "$old_value_path" || echo "")

if [ "$new_value" != "$old_value" ]; then
    git commit --allow-empty -m "$message ($new_value)"
    git push
fi
